# Generated by Django 4.1.5 on 2023-01-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie1app', '0002_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='img',
            new_name='images',
        ),
    ]
