# Generated by Django 4.1.5 on 2023-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie1app', '0003_rename_img_movie_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='images',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='ddffdfs', upload_to='pics'),
            preserve_default=False,
        ),
    ]
