# Generated by Django 4.1.5 on 2023-01-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie1app', '0004_remove_movie_images_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='img',
        ),
    ]
